"use client";
import Script from "next/script";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { CompetitionDetail, PublicSubmission } from "@/lib/types";

declare global { interface Window { PhonePeCheckout?: { transact(input:{tokenUrl:string;type:"IFRAME";callback:(response:string)=>void}):void } } }

export function CompetitionActions({competition,submission}:{competition:CompetitionDetail;submission?:PublicSubmission}){
  const [mode,setMode]=useState<"submit"|"vote"|null>(null);
  const [message,setMessage]=useState(""),[busy,setBusy]=useState(false);
  const router=useRouter(); const active=competition.status==="live"&&!competition.isShowcase;
  const close=()=>{setMode(null);setMessage("");setBusy(false)};
  async function submitEntry(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage("");const form=new FormData(event.currentTarget);form.set("competitionId",competition.id);const res=await fetch("/api/submissions",{method:"POST",body:form});const body=await res.json();if(!res.ok){setMessage(body.error??"Submission failed.");setBusy(false);return}setMessage("Entry published — best of luck!");router.refresh();setTimeout(close,1300)}
  async function payVote(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!submission)return;setBusy(true);setMessage("Creating secure ₹2 checkout…");const data=new FormData(event.currentTarget);const res=await fetch("/api/votes/phonepe/orders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({submissionId:submission.id,voterName:data.get("voterName"),voterPhone:data.get("voterPhone"),idempotencyKey:crypto.randomUUID()})});const body=await res.json();if(!res.ok){setMessage(body.error??"Could not start checkout.");setBusy(false);return}const poll=async()=>{for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,2000));const status=await fetch(`/api/votes/phonepe/orders/${body.statusToken}`).then(r=>r.json());if(status.state==="COMPLETED"){setMessage("Vote counted! 🎉");router.refresh();setTimeout(close,1500);return}if(["FAILED","EXPIRED","REFUNDED"].includes(status.state)){setMessage(`Payment ${status.state.toLowerCase()}.`);setBusy(false);return}}setMessage("Payment is still being verified. You can safely close this dialog.");setBusy(false)};
    if(window.PhonePeCheckout){window.PhonePeCheckout.transact({tokenUrl:body.redirectUrl,type:"IFRAME",callback:()=>void poll()})}else{location.href=body.redirectUrl}}
  return <><Script src="https://mercury.phonepe.com/web/bundle/checkout.js" strategy="lazyOnload"/>{submission?<button className="btn btn-secondary" style={{width:"100%",color:"var(--gold)",borderColor:"rgba(242,183,5,.4)"}} disabled={!active} onClick={()=>setMode("vote")}>{competition.isShowcase?"Showcase only":"Vote · ₹2"}</button>:<button className="btn btn-primary" disabled={!active} onClick={()=>setMode("submit")}>{competition.isShowcase?"Showcase only":"+ Submit Entry"}</button>}{mode&&<div onMouseDown={e=>e.target===e.currentTarget&&close()} style={{position:"fixed",inset:0,zIndex:100,display:"grid",placeItems:"center",padding:18,background:"rgba(3,1,2,.78)",backdropFilter:"blur(8px)"}}><div className="glass" role="dialog" aria-modal="true" style={{width:"min(470px,100%)",borderRadius:24,padding:28,animation:"vd-pop .35s ease both",background:"linear-gradient(165deg,#1c0e12,#120709)"}}><button onClick={close} aria-label="Close" style={{float:"right",border:0,background:"transparent",color:"var(--cream)",fontSize:22,cursor:"pointer"}}>×</button><div className="eyebrow">{mode==="submit"?"Submit Entry":"Cast Your Vote"}</div><h2 className="display" style={{margin:"8px 0 4px"}}>{mode==="submit"?competition.title:submission?.name}</h2><p className="muted" style={{fontSize:13}}> {mode==="vote"&&"One successful ₹2 payment equals one vote. Repeat after completion to vote again."}</p>{mode==="submit"?<form onSubmit={submitEntry}><label className="form-label">Name</label><input className="field" name="name" required/><label className="form-label">Phone</label><input className="field" name="phone" inputMode="tel" required/><label className="form-label">Email</label><input className="field" name="email" type="email" required/><label className="form-label">Submission photo</label><input className="field" name="photo" type="file" accept="image/jpeg,image/png,image/webp" required/><label className="form-label">Description</label><textarea className="field" name="description" rows={4} required/><button className="btn btn-primary" disabled={busy} style={{width:"100%",marginTop:18}}>{busy?"Publishing…":"Submit Entry"}</button></form>:<form onSubmit={payVote}><label className="form-label">Your name</label><input className="field" name="voterName" required/><label className="form-label">Your phone</label><input className="field" name="voterPhone" inputMode="tel" required/><button className="btn btn-primary" disabled={busy} style={{width:"100%",marginTop:18}}>{busy?"Please wait…":"Pay ₹2 & Vote"}</button></form>}{message&&<p role="status" style={{color:message.includes("failed")?"#ff8a8f":"var(--gold)",fontSize:13,textAlign:"center",marginBottom:0}}>{message}</p>}</div></div>}</>;
}
