"use server";
import { and, eq } from "drizzle-orm";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { start } from "workflow/api";
import { clearAdminSession, createAdminSession, requireAdmin, verifyAdminCredentials } from "@/lib/auth";
import { assertTrustedOrigin } from "@/lib/security";
import { checkRateLimit } from "@/lib/rate-limit";
import { getDb, hasDatabase } from "@/db";
import { adminAuditLog, competitions, events, submissions } from "@/db/schema";
import { istInputToUtc, slugify } from "@/lib/domain";
import { finalizeCompetitionWorkflow } from "@/workflows/finalize-competition";

export type LoginState={error?:string};
export async function loginAction(_:LoginState,form:FormData):Promise<LoginState>{await assertTrustedOrigin();const email=String(form.get("email")??""),password=String(form.get("password")??"");const limit=await checkRateLimit("admin-login",email.toLowerCase(),5,"15 m");if(!limit.success)return{error:"Too many attempts. Try again later."};if(!await verifyAdminCredentials(email,password))return{error:"Invalid admin credentials."};await createAdminSession(email);redirect("/admin")}
export async function logoutAction(){await requireAdmin();await clearAdminSession();redirect("/events")}

function ensureDb(){if(!hasDatabase())throw new Error("Connect Neon and run migrations before using admin mutations.");return getDb()}
export async function saveEventAction(form:FormData){await requireAdmin();await assertTrustedOrigin();const db=ensureDb();const id=String(form.get("id")??""),title=String(form.get("title")??"").trim(),description=String(form.get("description")??"").trim(),startsAt=istInputToUtc(String(form.get("startsAt")??"")),endsAt=istInputToUtc(String(form.get("endsAt")??""));if(title.length<3||!description||startsAt>=endsAt)throw new Error("Check the event title, description and dates.");if(id){await db.update(events).set({title,description,startsAt,endsAt,updatedAt:new Date()}).where(eq(events.id,id))}else{await db.insert(events).values({slug:`${slugify(title)}-${Date.now().toString(36)}`,title,description,startsAt,endsAt,glyph:"ಹೊ",banner:"linear-gradient(135deg,#3B0A12,#7a1622 55%,#b8341f)"})}await db.insert(adminAuditLog).values({action:id?"UPDATE_EVENT":"CREATE_EVENT",entityType:"event",entityId:id||title});revalidatePath("/events");revalidatePath("/admin/events")}
export async function archiveEventAction(form:FormData){await requireAdmin();const db=ensureDb(),id=String(form.get("id"));await db.update(events).set({publicationState:"ARCHIVED",updatedAt:new Date()}).where(eq(events.id,id));await db.insert(adminAuditLog).values({action:"ARCHIVE_EVENT",entityType:"event",entityId:id});revalidatePath("/events");revalidatePath("/admin/events")}
export async function saveCompetitionAction(form:FormData){await requireAdmin();await assertTrustedOrigin();const db=ensureDb();const id=String(form.get("id")??""),eventId=String(form.get("eventId")),title=String(form.get("title")??"").trim(),description=String(form.get("description")??"").trim(),rules=String(form.get("rules")??"").split("\n").map(v=>v.trim()).filter(Boolean),startsAt=istInputToUtc(String(form.get("startsAt")??"")),endsAt=istInputToUtc(String(form.get("endsAt")??"")),rawLimit=String(form.get("maxEntries")??"1"),maxEntriesPerParticipant=rawLimit===""?null:Number(rawLimit);const [event]=await db.select().from(events).where(eq(events.id,eventId)).limit(1);if(!event||title.length<3||!description||startsAt>=endsAt||startsAt<event.startsAt||endsAt>event.endsAt)throw new Error("Competition dates must be inside the parent event.");if(id){await db.update(competitions).set({eventId,title,description,rules,startsAt,endsAt,maxEntriesPerParticipant,updatedAt:new Date()}).where(eq(competitions.id,id))}else{await db.insert(competitions).values({eventId,slug:`${slugify(title)}-${Date.now().toString(36)}`,title,description,rules,startsAt,endsAt,maxEntriesPerParticipant,glyph:"ಹೊ",banner:"linear-gradient(135deg,#241030,#4A1E5C 55%,#7a2f8f)"})}await db.insert(adminAuditLog).values({action:id?"UPDATE_COMPETITION":"CREATE_COMPETITION",entityType:"competition",entityId:id||title});revalidatePath("/competitions");revalidatePath("/admin/competitions")}
export async function archiveCompetitionAction(form:FormData){await requireAdmin();const db=ensureDb(),id=String(form.get("id"));await db.update(competitions).set({lifecycle:"ARCHIVED",updatedAt:new Date()}).where(eq(competitions.id,id));await db.insert(adminAuditLog).values({action:"ARCHIVE_COMPETITION",entityType:"competition",entityId:id});revalidatePath("/competitions");revalidatePath("/admin/competitions")}
export async function moderateSubmissionAction(form:FormData){await requireAdmin();const db=ensureDb(),id=String(form.get("id")),state=String(form.get("state")) as "VISIBLE"|"HIDDEN";await db.update(submissions).set({state,updatedAt:new Date()}).where(eq(submissions.id,id));await db.insert(adminAuditLog).values({action:`SUBMISSION_${state}`,entityType:"submission",entityId:id});revalidatePath("/admin/submissions");revalidatePath("/competitions")}
export async function completeCompetitionAction(form:FormData){await requireAdmin();const db=ensureDb(),id=String(form.get("id"));const [competition]=await db.select().from(competitions).where(eq(competitions.id,id)).limit(1);if(!competition||competition.isShowcase||competition.lifecycle!=="PUBLISHED")return;await db.update(competitions).set({lifecycle:"CLOSING",completionStartedAt:new Date(),updatedAt:new Date()}).where(eq(competitions.id,id));const run=await start(finalizeCompetitionWorkflow,[id]);await db.insert(adminAuditLog).values({action:"START_COMPETITION_FINALIZATION",entityType:"competition",entityId:id,metadata:{runId:run.runId}});revalidatePath("/admin/leaderboard");revalidatePath("/competitions")}
